### ISSUE TITLE
Bounding Box not including Objects in nested Collections

### ISSUE THREAD

**Issue by regularlabs** [RayMairlot/Animated-Render-Border#17]
When using the 'Collection' tab, the Bounding Box only takes into account objects directly inside the selected collection.
It does not seem to find objects inside a nested collection structure.
Would it be possible to make that work?
That way I can keep using my 'folder' structure, like (all collections):
- Man
  - Body
  - Glasses
  - Clothes
     - Pants
     - Shirt
     - Shoes

**Comment by regularlabs** [comment]
Or alternatively:
Make it possible to select multiple collections.

**Comment by RayMairlot** [comment]
Duplicate of #10

**Comment by regularlabs** [comment]
Oops, sorry!
