### ISSUE TITLE
Render border not activated in Blender 3.1.0

### ISSUE THREAD

**Issue by Pablinimaxd** [RayMairlot/Animated-Render-Border#22]
Hi there!

First of all thank you for this amazing addon which I have used since blender 2.8. Unfortunately the addon is already installed in the blender 3.1.0 last update but I can't activate it, I mean it shows in the camera properties but I can't click to activate it, any ideas, thanks 
<img width="302" alt="Captura de Pantalla 2022-03-20 a la(s) 17 53 19" src="https://user-images.githubusercontent.com/92812221/159189578-78180f0a-c1d5-476c-838f-dbb743036bcc.png">

**Comment by RayMairlot** [comment]
Hi, 

As you have presumably realised, that is not my add-on 🙂.
