### ISSUE TITLE
Feature request : grid splitting

### ISSUE THREAD

**Issue by ChameleonScales** [RayMairlot/Animated-Render-Border#5]
It would be awesome if next to <kbd>Object</kbd><kbd>Group</kbd><kbd>Keyframe</kbd> there was a <kbd>Grid</kbd> tab where we can set up a grid splitting border. This would allow to split the frame in multiple tiles over time so we could render a still image over a network by having each machine render a part of it. Some renderfarms already do that but not all and neither does Blender's "Network Renderer" add-on.

**Comment by RayMairlot** [comment]
I'm not really sure that would fit with this add-on. "Object", "Group" and "Keyframe" are 3 different ways of animating the render border with the purpose of animating the render border over a sequence of frames, whereas your request is more about optimising a network render. I get that it's also about controlling the render border, but it's a bit different from what this add-on is aimed at.

That aside, I can't really see how it would work as this add-on would either have to be compatible with a network renderer that could specify which 'tile' of the grid each computer should render (and then combine all the different tiles into an image) or this add-on would have to handle all of that and the network rendering parts itself.

That doesn't seem very feasible or I'm misunderstanding something.

**Comment by ChameleonScales** [comment]
Thanks for your reply.
Actually my idea was more simple and in the scope of your add-on but I didn't explain the "over time" aspect enough.
The idea is to simply animate the render border so that in the first frame the border would cover a divided portion of the frame (like the top left quarter) and in the next frame the next portion, until the 4th quarter at the 4th frame. Of course this would only be useful in a still scene since we changed the frame, but anyway animations don't require to slice the frame unless you have more machines than you have frames, which very seldomly happens.
However I realize that at least Sheep it Renderfarm wouldn't be able to use it, since it already can't use the current features of your add-on (because it uses the regular render button).
At least it would work in [this kind of set up](https://youtu.be/y3EcpkwLCFI), but that wasn't my first purpose as there are already some tools to slice renders in local networks (Loki Render and the upcoming CrowdRender). My idea was more to use it on Sheep it since it splits the frame in an unconventional way that gets results that are hard to predict.

So I guess that's not useful at least as long as Sheep it allows no add-on.

**Comment by RayMairlot** [comment]
It's still not clear to me what the feature is, but I think the slicing of images is more suited to a network or batch rendering add-on.
