### ISSUE TITLE
AddOn crash Blender in v2.79

### ISSUE THREAD

**Issue by dr-brown** [RayMairlot/Animated-Render-Border#6]
If I want to enable the Addon in Blender 2.79 then Blender
crash immediately.

OS: Windows 7
Animated-Render-Border Version: 2.1 (master branch)

**Comment by RayMairlot** [comment]
I'm afraid I can't recreate this either with the latest 2.79 release candidate nor with the latest buildbot build of 2.79.

There are currently bugs in 2.79 related to add-ons which won't be in the final release, like https://developer.blender.org/T52564.

Are you able to start blender via the [Command Line](https://docs.blender.org/manual/de/dev/render/workflows/command_line.html) and then try enabling the add-on? This will mean the command line window will stay open even if blender crashes and will hopefully display any relevant error messages.

**Comment by dr-brown** [comment]
If I start Blender via command line (blender.exe --addons Animated-Render-Border) Blender 
don't crash but the addon is'nt enabled. The corresponding error message in the console is:
AttributeError: module 'Animated-Render-Border' has no attribute '__file__'

**Comment by RayMairlot** [comment]
You shouldn't have to add the `--addons` parameter. Just do the `blender.exe` command, then try enabling the add-on through the interface like normal and if it crashes see the error message. Apologies if I'm misunderstanding and that's what you already did.

And just to clarify, you installed the add-on by clicking the *Install from File...* button in the *User Preferences* and either installed the 'animatedRenderborder v2_1.py' or the 'animatedRenderborder.py' file (depending on if you bought it on the BlenderMarket or downloaded it from GitHub)?

**Comment by dr-brown** [comment]
Sorry for the misunderstanding. Now I have started blender without parameters and tried to
enable the addon; Blender crashes with the following message:
_pyrna_srna_ExternalType: incorrect subclassing of SRNA 'AddonPreferences'
See bpy_types.py
<Expected! > : Error: EXCEPTION_ACCESS_VIOLATION_
Yes, I installed the addon like you discribed it.

**Comment by RayMairlot** [comment]
I've had another look, but I'm afraid I still can't reproduce the issue. Are you using the latest version of 2.79 from https://builder.blender.org/download/ ? I'm using the latest version for Windows 64-bit. It may be worth downloading the latest one to see if something recently has fixed this issue as these builds of blender are generally updated daily.

Thanks for taking the time to investigate this issue with me.

**Comment by dr-brown** [comment]
I downloaded the latest build and now it works.

**Comment by RayMairlot** [comment]
I'm glad the issue has been solved. This is risk with using software releases before they have been officially released; they will likely be unstable as they are still being developed and existing functionality may temporarily break.
