### ISSUE TITLE
not working with 2.80 build from 2019-06-06

### ISSUE THREAD

**Issue by Tvaroog** [RayMairlot/Animated-Render-Border#8]
Hi, I tried it with a newest 2.80 build and got this error when pressing "Render Animation":

![animated_render_border_error](https://user-images.githubusercontent.com/51474569/59093676-ca6cf400-8914-11e9-83a1-8b75d9d1f74b.png)

**Comment by RayMairlot** [comment]
Thanks for reporting, this should be fixed now (though I can't promise everything works - I will be doing more fixes when 2.8 has been out for a while).
